services:
  hugo-site:
    build: .
    container_name: hugo-prod
    ports:
      - "8080:80"
    restart: unless-stopped

  hugo-dev:
    image: hugomods/hugo:latest
    container_name: hugo-dev
    command: server --bind 0.0.0.0 --port 1313 --baseURL http://localhost:1313 --watch --disableFastRender --gc --cleanDestinationDir
    ports:
      - "1313:1313"
    volumes:
      - .:/src
